version: '3.7'
services:
  brotato-exporter:
    build: .
    ports:
      - 8080:8080 # api
      - 8081:8081 # pprof
    volumes:
      - ./var-brotatoexporter:/var/brotatoexporter
      - ./var-brotatoexporter/log:/var/log
    restart: unless-stopped
    