package brotatomodtypes

// CharacterType character type ID in the game
type CharacterType string

const (
	CharacterNone             CharacterType = "-"
	CharacterTypeWellRounded  CharacterType = "character_well_rounded"
	CharacterTypeBrawler      CharacterType = "character_brawler"
	CharacterTypeCrazy        CharacterType = "character_crazy"
	CharacterTypeRanger       CharacterType = "character_ranger"
	CharacterTypeMage         CharacterType = "character_mage"
	CharacterTypeOneArm       CharacterType = "character_one_arm"
	CharacterTypeBull         CharacterType = "character_bull"
	CharacterTypeSoldier      CharacterType = "character_soldier"
	CharacterTypeMasochist    CharacterType = "character_masochist"
	CharacterTypeKnight       CharacterType = "character_knight"
	CharacterTypeDemon        CharacterType = "character_demon"
	CharacterTypeOld          CharacterType = "character_old"
	CharacterTypeMutant       CharacterType = "character_mutant"
	CharacterTypeLoud         CharacterType = "character_loud"
	CharacterTypeWildling     CharacterType = "character_wildling"
	CharacterTypeGladiator    CharacterType = "character_gladiator"
	CharacterTypeLucky        CharacterType = "character_lucky"
	CharacterTypeGeneralist   CharacterType = "character_generalist"
	CharacterTypeMultitasker  CharacterType = "character_multitasker"
	CharacterTypePacifist     CharacterType = "character_pacifist"
	CharacterTypeSaver        CharacterType = "character_saver"
	CharacterTypeChunky       CharacterType = "character_chunky"
	CharacterTypeSick         CharacterType = "character_sick"
	CharacterTypeFarmer       CharacterType = "character_farmer"
	CharacterTypeGhost        CharacterType = "character_ghost"
	CharacterTypeSpeedy       CharacterType = "character_speedy"
	CharacterTypeEntrepreneur CharacterType = "character_entrepreneur"
	CharacterTypeEngineer     CharacterType = "character_engineer"
	CharacterTypeExplorer     CharacterType = "character_explorer"
	CharacterTypeDoctor       CharacterType = "character_doctor"
	CharacterTypeHunter       CharacterType = "character_hunter"
	CharacterTypeArtificer    CharacterType = "character_artificer"
	CharacterTypeArmsDealer   CharacterType = "character_arms_dealer"
	CharacterTypeStreamer     CharacterType = "character_streamer"
	CharacterTypeGlutton      CharacterType = "character_glutton"
	CharacterTypeCyborg       CharacterType = "character_cyborg"
	CharacterTypeJack         CharacterType = "character_jack"
	CharacterTypeLich         CharacterType = "character_lich"
	CharacterTypeFisherman    CharacterType = "character_fisherman"
	CharacterTypeCryptid      CharacterType = "character_cryptid"
	CharacterTypeKing         CharacterType = "character_king"
	CharacterTypeApprentice   CharacterType = "character_apprentice"
	CharacterTypeGolem        CharacterType = "character_golem"
	CharacterTypeRenegade     CharacterType = "character_renegade"
	CharacterTypeBaby         CharacterType = "character_baby"
	CharacterTypeVagabond     CharacterType = "character_vagabond"
	CharacterTypeTechnomage   CharacterType = "character_technomage"
	CharacterTypeVampire      CharacterType = "character_vampire"
)
